  - name: apiserver
    image: gcr.io/google_containers/hyperkube-amd64:v1.4.6
    command:
    - "/hyperkube"
    - apiserver
    - "--service-cluster-ip-range=10.0.0.1/24"
#    - "--insecure-bind-address=0.0.0.0"
    - "--secure-port=443"
    - "--etcd-servers=http://127.0.0.1:2379"
    - "--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota"
    - "--min-request-timeout=300"
    - "--tls-cert-file=/etc/kubernetes/ssl/apiserver.pem"
    - "--tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem"
    - "--client-ca-file=/etc/kubernetes/ssl/ca.pem"
    - "--service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem"
    - "--allow-privileged=true"
    - "--v=2"
    volumeMounts:
    - name: kubernetes-ssl
      mountPath: /etc/kubernetes/ssl
  volumes:
  - name: kubernetes-ssl
    hostPath:
      path: /opt/kubernetes/ssl
