---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-master
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube-amd64:v1.4.6
    command:
    - /hyperkube
    - proxy
    - --master=http://masterip:8080
    - --proxy-mode=iptables
    securityContext:
      privileged: true
